name: CI/CD - FastAPI + Streamlit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # -------------------------
  # 1) TESTS
  # -------------------------
  tests:
    name: Run API tests (pytest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest  # <-- Ajouté pour garantir que pytest est installé

      - name: Run tests
        run: |
          pytest api/tests -q

  # -------------------------
  # 2) BUILD DOCKER IMAGE
  # -------------------------
  docker-build:
    name: Build Docker image (FastAPI)
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        run: |
          docker build -t crop-api:latest ./api

  # -------------------------
  # 3) PUSH DOCKER HUB (optionnel)
  # -------------------------
  docker-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crop-api:latest
